# Generated by Django 5.1.7 on 2025-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleParLot',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_creation', models.DateField(auto_now_add=True, db_column='Date_creation', null=True)),
                ('heure_creation', models.TimeField(auto_now_add=True, db_column='Heure_creation', null=True)),
            ],
            options={
                'db_table': 'Article_par_lot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, db_column='Date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='Date_fin', null=True)),
                ('status_of', models.TextField(blank=True, db_column='Status_OF', null=True)),
            ],
            options={
                'db_table': 'Ordre_fabrication',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
    ]
