# Generated by Django 5.1.7 on 2025-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_entree', models.DateField(blank=True, db_column='Date_entree', null=True)),
                ('heure_entree', models.TimeField(blank=True, db_column='Heure_entree', null=True)),
                ('date_sortie', models.DateField(blank=True, db_column='Date_sortie', null=True)),
                ('heure_sortie', models.TimeField(blank=True, db_column='Heure_sortie', null=True)),
                ('poids_in', models.BigIntegerField(blank=True, db_column='Poids_in', null=True)),
                ('poids_out', models.BigIntegerField(blank=True, db_column='Poids_out', null=True)),
                ('poids_net', models.BigIntegerField(blank=True, db_column='Poids_net', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('numero_interne', models.BigIntegerField(blank=True, db_column='Numero_interne', null=True)),
            ],
            options={
                'db_table': 'Camion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chargement',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date_debut', models.DateField(blank=True, db_column='Date_debut', null=True)),
                ('date_fin', models.DateField(blank=True, db_column='Date_fin', null=True)),
                ('numero_chargement', models.BigIntegerField(blank=True, db_column='Numero_chargement', null=True)),
                ('chargement_dechargement', models.TextField(blank=True, db_column='Chargement/Dechargement', null=True)),
                ('client', models.TextField(blank=True, db_column='Client', null=True)),
                ('adresse_livraison', models.TextField(blank=True, db_column='Adresse livraison', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
            ],
            options={
                'db_table': 'Chargement',
                'managed': False,
            },
        ),
    ]
