# Generated by Django 5.1.7 on 2025-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_article', models.BigIntegerField(db_column='Numero_article')),
                ('description_article', models.TextField(db_column='Description_article')),
                ('front_back', models.TextField(blank=True, db_column='Front/Back', null=True)),
                ('nomenclature', models.BigIntegerField(blank=True, db_column='Nomenclature', null=True)),
                ('categorie', models.TextField(blank=True, db_column='Categorie', null=True)),
            ],
            options={
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lot', models.BigIntegerField(blank=True, db_column='Lot', null=True)),
                ('date_modification', models.DateField(blank=True, db_column='Date_modification', null=True)),
                ('heure_modification', models.TimeField(blank=True, db_column='Heure_modification', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'Lot',
                'managed': False,
            },
        ),
    ]
