# Generated by Django 5.1.7 on 2025-05-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rerun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Lot',
        ),
        migrations.DeleteModel(
            name='OrdreFabrication',
        ),
    ]
