# Generated by Django 5.1.7 on 2025-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('numero_article', models.BigIntegerField(db_column='Numero_article')),
                ('description_article', models.TextField(db_column='Description_article')),
                ('front_back', models.TextField(blank=True, db_column='Front/Back', null=True)),
                ('categorie', models.TextField(blank=True, db_column='Categorie', null=True)),
            ],
            options={
                'db_table': 'Article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Nomenclature',
                'managed': False,
            },
        ),
    ]
