# Generated by Django 5.1.7 on 2025-05-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': False, 'ordering': ['numero_article']},
        ),
    ]
