# Generated by Django 5.1.7 on 2025-05-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nomenclature',
            options={'managed': False, 'ordering': ['id_article__numero_article']},
        ),
    ]
